# Generated by Django 5.1 on 2024-10-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_nom', models.CharField(max_length=200)),
                ('persona_cognom1', models.CharField(max_length=100)),
                ('persona_data_naixement', models.DateTimeField(verbose_name='Data de naixement')),
            ],
        ),
    ]
